version: "3.8"
services:
  deno-server:
    build: .
    environment:
      - PGHOST=timescaledb
      - PGDATABASE=location_tracker
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGPORT=5432
    ports:
      - "8000:8000"
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=location_tracker
    volumes:
      - timescaledb_data:/home/postgres/pgdata/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  timescaledb_data:
